# Generated by Django 3.2.8 on 2022-03-01 08:27

from django.db import migrations, models
import django.db.models.deletion
import portalapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default='', max_length=250)),
                ('lastName', models.CharField(blank=True, default='', max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phoneNos', models.CharField(blank=True, default='', max_length=250)),
                ('registerCourse', models.CharField(blank=True, default='', max_length=250)),
                ('address', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EachTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(blank=True, default='', max_length=1000)),
                ('File', models.FileField(blank=True, upload_to=portalapp.models.upload_location, verbose_name='File')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('submit_date', models.DateField()),
                ('course', models.CharField(blank=True, default='', max_length=1000)),
                ('Reviews', models.TextField(blank=True, default='', max_length=1000)),
                ('Task_completed', models.BooleanField(default=False)),
                ('Task_status', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('Approve', 'Approve'), ('Review', 'Review'), ('Pending', 'Pending')], default='Pending', max_length=1000)),
                ('Task_nos', models.IntegerField(default=0)),
                ('EachUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_set', to='portalapp.alluser')),
            ],
            options={
                'ordering': ('-Task', '-start_date'),
            },
        ),
    ]
