# Generated by Django 3.2.8 on 2022-03-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eachtask',
            name='Scores',
            field=models.IntegerField(default=0),
        ),
    ]
