# Generated by Django 3.2.8 on 2022-03-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_eachtask_scores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
