# Generated by Django 3.2.8 on 2022-03-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0005_auto_20220301_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='registerCourse',
            new_name='registered_Course',
        ),
        migrations.RemoveField(
            model_name='eachtask',
            name='Task_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
