# Generated by Django 3.2.8 on 2022-03-08 11:53

from django.db import migrations, models
import portalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0006_auto_20220302_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default='', max_length=250)),
                ('File', models.FileField(blank=True, upload_to=portalapp.models.upload_location, verbose_name='File')),
            ],
        ),
    ]
