# Generated by Django 3.2.8 on 2022-03-08 16:25

from django.db import migrations, models
import portalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0007_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=portalapp.models.upload_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
