# Generated by Django 3.2.8 on 2022-03-09 07:44

from django.db import migrations, models
import portalapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0008_auto_20220308_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=portalapp.models.upload_path),
        ),
    ]
