# Generated by Django 3.2.8 on 2022-03-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0009_auto_20220309_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
