# Generated by Django 3.2.8 on 2022-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0011_auto_20220317_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachtask',
            name='phone_nos',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
